POPUP = "//*[@id='close-button-1454703513202']/span"
GENDER = "//a[@class='menu-header-item__title'][normalize-space()='BEBEK']"
CATEGORYS =  "//span[normalize-space()='(0-12 AY)']"
CATEGORY = "//*[@id='header__container']/header/div[3]/nav/ul/li[4]/div/nav/section/div[1]/div[2]/ul/li[16]/a"
PRODUCT = "//h5[contains(text(),'Standart Kalıp Kız Bebek Şort Etek')]"
ADDSIZE = "//*[@id='option-size']/a[7]"  
ADD_TO_CART = "//a[@id='pd_add_to_cart']"
CART = "//span[normalize-space()='Sepetim']"
HOMEPAGE = "//a[@class='main-header-logo']//*[name()='svg']"